<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<a class="brand" href="#"><?php echo $this->title ?></a>
		<ul class="nav">
			<li class="divider-vertical"><a href="<?php echo $this->url('home') ?>">Inicio</a></li>
			<li class="active divider-vertical"><a 
												 href="<?php echo $this->basePath() . 
												 '/application/lists/otroLayout' ?>">
													Otro layout
												</a>
			</li> 
			<li class="divider-vertical"><a href="<?php echo $this->basePath() . 
												 '/application/lists/recibeParametros' ?>">
											Recibe parametros
										</a>
			</li> 
		</ul>
	</div>
</div>