<?php echo $this->doctype() ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate($this->title))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
						->prependStylesheet($this->basePath() . '/css/style.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
		<!--header-->
		<?php echo $this->partial('layout/header.phtml', array('title' => $this->title)) ?>
		<!--/header-->
		
		<!--content-->
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
			
			<!--footer-->
            <?php echo $this->partial('layout/footer.phtml') ?>
			<!--/footer-->
        </div> 
		<!-- /container -->
		
        <?php echo $this->inlineScript()->prependFile($this->basePath() . '/file/in_to/body.js') ?>
    </body>
</html>
